use crate::compare::{CaseResult, Status};
use anyhow::{Context, Result};
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::Path;

/// What one `parity run` on one machine produced.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RunResults {
    /// `windows` or `mac`.
    pub platform: String,
    /// The GPU adapter wgpu rendered with.
    pub adapter: String,
    /// `harness-info.json` from the references, verbatim.
    #[serde(default)]
    pub references: serde_json::Value,
    pub cases: Vec<CaseResult>,
}

impl RunResults {
    pub fn load(path: &Path) -> Result<Self> {
        serde_json::from_slice(&std::fs::read(path)?).with_context(|| format!("reading {}", path.display()))
    }
    pub fn count(&self, status: Status) -> usize {
        self.cases.iter().filter(|c| c.status == status).count()
    }
}

#[derive(Debug, Deserialize)]
pub struct FeatureList {
    #[serde(rename = "feature")]
    pub features: Vec<Feature>,
}

#[derive(Debug, Deserialize)]
pub struct Feature {
    pub key: String,
    pub name: String,
    /// Port sources whose changes should re-run this feature's cases.
    #[serde(default)]
    pub paths: Vec<String>,
    /// Differences we know about and have documented, each a sentence or two.
    #[serde(default)]
    pub gaps: Vec<String>,
}

impl FeatureList {
    pub fn load(path: &Path) -> Result<Self> {
        toml::from_str(&std::fs::read_to_string(path)?).with_context(|| format!("reading {}", path.display()))
    }
}

/// Cases that passed in `baseline` and don't pass now.
pub fn regressions<'a>(baseline: &RunResults, current: &'a RunResults) -> Vec<&'a CaseResult> {
    let before: BTreeMap<&str, Status> = baseline.cases.iter().map(|c| (c.id.as_str(), c.status)).collect();
    current
        .cases
        .iter()
        .filter(|c| before.get(c.id.as_str()) == Some(&Status::Pass) && c.status != Status::Pass)
        .collect()
}

fn status_word(s: Status) -> &'static str {
    match s {
        Status::Pass => "pass",
        Status::Fail => "**fail**",
        Status::Pending => "pending",
        Status::Error => "**error**",
    }
}

/// The per-run report posted to the job summary: totals, then every case that isn't passing.
pub fn run_markdown(results: &RunResults, regressions: &[&CaseResult]) -> String {
    let mut md = String::new();
    let total = results.cases.len();
    let _ = writeln!(md, "## Parity on {} ({})\n", results.platform, results.adapter);
    let _ = writeln!(
        md,
        "{} of {} cases pass, {} fail, {} pending, {} errors, {} regressions.\n",
        results.count(Status::Pass),
        total,
        results.count(Status::Fail),
        results.count(Status::Pending),
        results.count(Status::Error),
        regressions.len()
    );
    if !regressions.is_empty() {
        let _ = writeln!(md, "### Regressions\n");
        for r in regressions {
            let _ = writeln!(md, "- `{}` now {}", r.id, status_word(r.status));
        }
        md.push('\n');
    }
    let failing: Vec<&CaseResult> =
        results.cases.iter().filter(|c| matches!(c.status, Status::Fail | Status::Error)).collect();
    if !failing.is_empty() {
        let _ = writeln!(md, "### Not passing\n");
        let _ = writeln!(md, "| Case | Result | Max diff | Pixels over | Tolerance | Detail |");
        let _ = writeln!(md, "| --- | --- | --- | --- | --- | --- |");
        for c in failing {
            let pixels = match (c.differing_pixels, c.total_pixels) {
                (Some(d), Some(t)) => format!("{d} of {t}"),
                _ => String::new(),
            };
            let _ = writeln!(
                md,
                "| `{}` | {} | {} | {} | {}/255 | {} |",
                c.id,
                status_word(c.status),
                c.max_channel_diff.map(|d| format!("{d}/255")).unwrap_or_default(),
                pixels,
                c.tolerance,
                c.message.as_deref().unwrap_or("").replace('|', "\\|")
            );
        }
    }
    md
}

/// PARITY.md: per-feature status across both platforms, the overall percentage, and known gaps.
pub fn parity_markdown(features: &FeatureList, runs: &[RunResults], overrides: &[crate::compare::Override], commit: &str) -> String {
    let mut md = String::new();
    let _ = writeln!(md, "# Parity\n");
    let _ = writeln!(
        md,
        "This file is regenerated by CI from the parity run at `{commit}`. Don't edit it by hand: \
         change `parity/features.toml` for feature names and known gaps, and `parity/tolerances.toml` for overrides.\n"
    );
    let _ = writeln!(
        md,
        "A case passes when every pixel matches the Mac app's own rendering within 1/255 per channel, \
         unless an override below says otherwise. See `parity/README.md` for how cases are built and compared.\n"
    );
    let total_cases = runs.iter().map(|r| r.cases.len()).max().unwrap_or(0);
    let _ = writeln!(md, "## Overall\n");
    for run in runs {
        let pass = run.count(Status::Pass);
        let pct = if run.cases.is_empty() { 0.0 } else { 100.0 * pass as f64 / run.cases.len() as f64 };
        let _ = writeln!(md, "- **{}** ({}): {pct:.1}% ({pass} of {} cases)", run.platform, run.adapter, run.cases.len());
    }
    if runs.is_empty() {
        let _ = writeln!(md, "No parity run has completed yet.");
    }
    let _ = writeln!(md, "\n## By feature\n");
    let mut header = String::from("| Feature | Cases |");
    let mut rule = String::from("| --- | --- |");
    for run in runs {
        let _ = write!(header, " {} |", run.platform);
        rule.push_str(" --- |");
    }
    let _ = writeln!(md, "{header}\n{rule}");
    for f in &features.features {
        let n = runs
            .first()
            .map(|r| r.cases.iter().filter(|c| c.feature == f.key).count())
            .unwrap_or(0);
        let mut row = format!("| {} | {n} |", f.name);
        for run in runs {
            let cases: Vec<&CaseResult> = run.cases.iter().filter(|c| c.feature == f.key).collect();
            let pass = cases.iter().filter(|c| c.status == Status::Pass).count();
            let cell = if cases.is_empty() {
                "no cases".to_string()
            } else if pass == cases.len() {
                format!("✅ {pass}/{}", cases.len())
            } else if cases.iter().all(|c| c.status == Status::Pending) {
                format!("not started 0/{}", cases.len())
            } else {
                format!("{pass}/{}", cases.len())
            };
            let _ = write!(row, " {cell} |");
        }
        let _ = writeln!(md, "{row}");
    }
    let _ = writeln!(md, "\nTotal: {total_cases} cases.\n");
    let _ = writeln!(md, "## Known gaps\n");
    let mut any = false;
    for f in &features.features {
        for gap in &f.gaps {
            let _ = writeln!(md, "- **{}**: {gap}", f.name);
            any = true;
        }
    }
    if !any {
        let _ = writeln!(md, "None recorded.");
    }
    let _ = writeln!(md, "\n## Tolerance overrides\n");
    if overrides.is_empty() {
        let _ = writeln!(md, "None. Every case is held to 1/255.");
    } else {
        let _ = writeln!(md, "| Cases | Limit | Reason |\n| --- | --- | --- |");
        for o in overrides {
            let _ = writeln!(md, "| `{}` | {}/255 | {} |", o.cases, o.max_channel_diff, o.reason);
        }
    }
    let _ = writeln!(md, "\n## References\n");
    for run in runs.iter().take(1) {
        let info = &run.references;
        let metal = info.get("metalDevice").and_then(|v| v.as_str()).unwrap_or("none");
        let os = info.get("macOS").and_then(|v| v.as_str()).unwrap_or("unknown");
        let _ = writeln!(md, "Rendered by the Mac app's code on macOS {os}; Metal device: {metal}.");
    }
    md
}
