[package]
name = "app"
edition.workspace = true
version.workspace = true
license.workspace = true

[[bin]]
name = "compositor"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
clap.workspace = true
image.workspace = true
pollster.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true
uuid.workspace = true
wgpu.workspace = true
comp-format.workspace = true
engine.workspace = true
eframe = { version = "0.36", default-features = false, features = ["wgpu", "default_fonts", "accesskit", "x11", "wayland"] }
egui-phosphor = { version = "0.14", default-features = false, features = ["regular", "fill"] }
rfd = "0.17"
